config/routes.rb
Rails.application.routes.draw do
  get 'pages/secret'
  get 'pages/contact'
  get 'pages/team'
  root 'gossips#index'

  resources :tags
  resources :private_messages
  resources :likes
  resources :gossips do
    post 'like', on: :member
    delete 'dislike', on: :member
  end
  resources :comments
  resources :cities

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end
  
  get '/contact', to: 'pages#contact'
  get '/secret', to: 'pages#secret'
  get '/team', to: 'pages#team'
  
  namespace :admin do
    get 'dashboard/index'
    resources :users
    resources :gossips
    # Ajoutez d'autres ressources pour l'administration si nécessaire
  end
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
end

app/controllers/admin/gossips_controller.rb
module Admin
  class GossipsController < ApplicationController
    before_action :set_gossip, only: %i[ show edit update destroy ]

    # GET /admin/gossips or /admin/gossips.json
    def index
      @gossips = Gossip.all
    end

    # GET /admin/gossips/1 or /admin/gossips/1.json
    def show
    end

    # GET /admin/gossips/new
    def new
      @gossip = Gossip.new
    end

    # GET /admin/gossips/1/edit
    def edit
    end

    # POST /admin/gossips or /admin/gossips.json
    def create
      @gossip = Gossip.new(gossip_params)

      respond_to do |format|
        if @gossip.save
          format.html { redirect_to admin_gossip_url(@gossip), notice: "Gossip was successfully created." }
          format.json { render :show, status: :created, location: admin_gossip_url(@gossip) }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @gossip.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/gossips/1 or /admin/gossips/1.json
    def update
      respond_to do |format|
        if @gossip.update(gossip_params)
          format.html { redirect_to admin_gossip_url(@gossip), notice: "Gossip was successfully updated." }
          format.json { render :show, status: :ok, location: admin_gossip_url(@gossip) }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @gossip.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/gossips/1 or /admin/gossips/1.json
    def destroy
      @gossip.destroy

      respond_to do |format|
        format.html { redirect_to admin_gossips_url, notice: "Gossip was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_gossip
        @gossip = Gossip.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def gossip_params
        params.require(:gossip).permit(:title, :content, :user_id)
      end
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :set_gossip, only: %i[show edit update destroy]
  before_action :require_login, only: %i[new create edit update destroy]
  before_action :authorize_user, only: %i[edit update destroy]

  def index
    @gossips = Gossip.all
    @comments = Comment.all
    @likes = Like.all
  end

  def show
    
    @gossip = Gossip.find_by_id(params[:id])
    if @gossip
      @comment = Comment.new
      @comments = @gossip.comments
    else
      redirect_to gossips_path, alert: "Le potin que vous essayez d'afficher n'existe pas."
    end
  end

  def new
    @gossip = Gossip.new
    @user_id = current_user.id
  end

  def create
    @gossip = current_user.gossips.build(gossip_params)
    if @gossip.save
      flash[:success] = "Gossip created"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(gossip_params)
      redirect_to gossips_path
    else
      render 'edit'
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  def user_gossips
    @user = User.find(params[:user_id])
    @gossips = @user.gossips
  end

  def like
    @gossip = Gossip.find(params[:id])
    @like = Like.new(gossip: @gossip, user: current_user)
    if @like.save
      flash[:success] = "Gossip liked"
    else
      flash[:danger] = "Failed to like gossip"
    end
    redirect_to gossip_path(@gossip)
  end

  def dislike
    @gossip = Gossip.find(params[:id])
    @like = Like.find_by(gossip: @gossip, user: current_user)
    if @like.destroy
      flash[:success] = "Gossip disliked"
    else
      flash[:danger] = "Failed to dislike gossip"
    end
    redirect_to gossip_path(@gossip)
  end

  private

  def set_gossip
    @gossip = Gossip.find(params[:id])
  end

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end

  def require_login
    unless logged_in?
      flash[:danger] = "Please log in"
      redirect_to root_path
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def authorize_user
    @gossip = Gossip.find(params[:id])
    unless @gossip.user == current_user
      flash[:danger] = "You are not authorized to perform this action"
      redirect_to root_path
    end
  end
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/_form.html.erb
<%= form_with(model: gossip, class: "form-card") do |form| %>
  <% if gossip.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(gossip.errors.count, "error") %> prohibited this gossip from being saved:</h2>

      <ul>
        <% gossip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gossips/_gossip.html.erb
<div id="<%= dom_id(gossip) %>" class="form-card">
  <h2>Gossip Details</h2>
  <br>
  <p>
    <strong>Title:</strong>
    <%= gossip.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= gossip.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= gossip.user.first_name %>
    <%= gossip.user.last_name %>
  </p>
</div>

app/views/gossips/edit.html.erb
<h1>Editing gossip</h1>

<%= render "form", gossip: @gossip %>

<br>

<div>
  <%= button_to "Show this gossip", @gossip, method: :get, class: "actions" %> 
  <%= button_to "Back to gossips", gossips_path, method: :get, class: "actions" %>
</div>

app/views/gossips/index.html.erb
<main>
  <% if user_signed_in? %>
    <div class="welcome">
      <p>Bienvenue <%= current_user.first_name %> ! Vous êtes maintenant connecté.</p>
    </div>
  <% end %>

  <h1 class="text-center"><span class="color-h1">Bienvenue sur</span> XOXO <span class="color-h1">Gossip Project</span></h1>
  <p class="text-center">Parcourez le mur des gossips pour voir les dernières nouveautés</p>

  <% if user_signed_in? %>
    <%= link_to "New Gossip", new_gossip_path(user_id: current_user.try(:id)), class: "like-button" %>
  <% end %>
  <br>
  <br>
  <% @gossips.each do |gossip| %>
    <div class="gossip-card">
      <article>
        <div class="gossip-header">
          <h2><%= gossip.title %></h2>
          <p class="gossip-author">Par <%= gossip.user.first_name %></p>
        </div>
        <div class="gossip-actions">
          <div class="gossip-buttons">
            <button class="actions" onclick="window.location.href='<%= gossip_path(gossip) %>'">
              Voir le potin
            </button>
            <%= turbo_frame_tag "like-frame-#{gossip.id}" do %>
              <%= button_to like_gossip_path(gossip), method: :post, class: "like-button" do %>
                <i class="fas fa-thumbs-up"></i>
                <span class="like-count"><%= gossip.likes.count %></span>
              <% end %>
            <% end %>
          </div>
          <div class="comments-section">
            <ul class="comment-list">
              <% gossip.comments.each do |comment| %>
                <li class="comment">
                  <div class="comment-author">
                    <strong><%= comment.user.first_name %></strong>
                  </div>
                  <div class="comment-content">
                    <%= comment.content %>
                  </div>
                  <% if user_signed_in? && current_user == comment.user %>
                    <div class="comment-actions">
                      <%= link_to "Edit", edit_comment_path(comment), class: "edit-comment" %>
                      <%= link_to "Delete", comment_path(comment), method: :delete, data: { confirm: "Are you sure?" }, class: "delete-comment" %>
                    </div>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
          <% if user_signed_in? %>
            <%= form_with(model: Comment.new, url: comments_path, class: "comment-form") do |form| %>
              <%= form.text_area :content, placeholder: "Add a comment...", rows: 2, class: "comment-input" %>
              <%= form.hidden_field :gossip_id, value: gossip.id %>
              <%= form.submit "Post", class: "comment-button" %>
            <% end %>
          <% end %>
        </div>
      </article>
    </div>
  <% end %>
</main>

app/views/gossips/new.html.erb
<div class="form-card">
  <h1>New gossip</h1>
  <br>
  <%= form_with(model: @gossip) do |form| %>
    <% if @gossip.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@gossip.errors.count, "error") %> prohibited this gossip from being saved:</h2>

        <ul>
          <% @gossip.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :content, style: "display: block" %>
      <%= form.text_area :content %>
    </div>

    <div class="field">
      <%= form.label :user_first_name, style: "display: block" %>
      <%= form.text_field :user_first_name %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  <br>

    <div>
    <%= link_to "Back to gossips", gossips_path %>
    </div>

</div>

app/views/gossips/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @gossip %>

<div>
  <%= button_to "Edit this gossip", edit_gossip_path(@gossip), method: :get, class: "actions" %>
  <%= button_to "Back to gossips", gossips_path, method: :get, class: "actions" %>
  <%= button_to "Destroy this gossip", @gossip, method: :delete, class: "actions" %>
</div>