config/routes.rb
Rails.application.routes.draw do
  get 'pages/secret'
  get 'pages/contact'
  get 'pages/team'
  root 'gossips#index'

  resources :tags
  resources :private_messages
  resources :likes
  resources :gossips do
    post 'like', on: :member
    delete 'dislike', on: :member
  end
  resources :comments
  resources :cities

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end
  
  get '/contact', to: 'pages#contact'
  get '/secret', to: 'pages#secret'
  get '/team', to: 'pages#team'
  
  namespace :admin do
    get 'dashboard/index'
    resources :users
    resources :gossips
    # Ajoutez d'autres ressources pour l'administration si nécessaire
  end
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/controllers/private_messages_controller.rb
class PrivateMessagesController < ApplicationController
  before_action :set_private_message, only: %i[ show edit update destroy ]

  # GET /private_messages or /private_messages.json
  def index
    @private_messages = PrivateMessage.all
  end

  # GET /private_messages/1 or /private_messages/1.json
  def show
  end

  # GET /private_messages/new
  def new
    @private_message = PrivateMessage.new
  end

  # GET /private_messages/1/edit
  def edit
  end

  # POST /private_messages or /private_messages.json
  def create
    @private_message = PrivateMessage.new(private_message_params)

    respond_to do |format|
      if @private_message.save
        format.html { redirect_to private_message_url(@private_message), notice: "Private message was successfully created." }
        format.json { render :show, status: :created, location: @private_message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @private_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /private_messages/1 or /private_messages/1.json
  def update
    respond_to do |format|
      if @private_message.update(private_message_params)
        format.html { redirect_to private_message_url(@private_message), notice: "Private message was successfully updated." }
        format.json { render :show, status: :ok, location: @private_message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @private_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /private_messages/1 or /private_messages/1.json
  def destroy
    @private_message.destroy

    respond_to do |format|
      format.html { redirect_to private_messages_url, notice: "Private message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_private_message
      @private_message = PrivateMessage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def private_message_params
      params.require(:private_message).permit(:content, :sender_id, :recipient_id)
    end
end

app/helpers/private_messages_helper.rb
module PrivateMessagesHelper
end

app/views/private_messages/_form.html.erb
<%= form_with(model: private_message) do |form| %>
  <% if private_message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(private_message.errors.count, "error") %> prohibited this private_message from being saved:</h2>

      <ul>
        <% private_message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :sender_id, style: "display: block" %>
    <%= form.text_field :sender_id %>
  </div>

  <div>
    <%= form.label :recipient_id, style: "display: block" %>
    <%= form.text_field :recipient_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/private_messages/_private_message.html.erb
<div id="<%= dom_id private_message %>">
  <p>
    <strong>Content:</strong>
    <%= private_message.content %>
  </p>

  <p>
    <strong>Sender:</strong>
    <%= private_message.sender_id %>
  </p>

  <p>
    <strong>Recipient:</strong>
    <%= private_message.recipient_id %>
  </p>

</div>

app/views/private_messages/edit.html.erb
<h1>Editing private message</h1>

<%= render "form", private_message: @private_message %>

<br>

<div>
  <%= link_to "Show this private message", @private_message %> |
  <%= link_to "Back to private messages", private_messages_path %>
</div>

app/views/private_messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Private messages</h1>

<div id="private_messages">
  <% @private_messages.each do |private_message| %>
    <%= render private_message %>
    <p>
      <%= link_to "Show this private message", private_message %>
    </p>
  <% end %>
</div>

<%= link_to "New private message", new_private_message_path %>

app/views/private_messages/new.html.erb
<h1>New private message</h1>

<%= render "form", private_message: @private_message %>

<br>

<div>
  <%= link_to "Back to private messages", private_messages_path %>
</div>

app/views/private_messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @private_message %>

<div>
  <%= link_to "Edit this private message", edit_private_message_path(@private_message) %> |
  <%= link_to "Back to private messages", private_messages_path %>

  <%= button_to "Destroy this private message", @private_message, method: :delete %>
</div>